const express = require('express');
const router = express.Router();

const adminAuth = require('./adminAuth');
const adminDashboard = require('./adminDashboard');
const adminBranches = require('./adminBranches');
const adminManagers = require('./adminManagers');
const adminFieldVisitors = require('./adminFieldVisitors');
const adminMembers = require('./adminMembers');
const adminProducts = require('./adminProducts');
const adminTransactions = require('./adminTransactions');
const adminWallets = require('./adminWallets');
const adminCompanyTransfers = require('./adminCompanyTransfers');
const adminReports = require('./adminReports');
const adminGeoTracking = require('./adminGeoTracking');
const adminTasks = require('./adminTasks');
const adminAttendance = require('./adminAttendance');
const adminNotifications = require('./adminNotifications');
const adminLogs = require('./adminLogs');
const adminFraudAlerts = require('./adminFraudAlerts');
const adminAnalytics = require('./adminAnalytics');
const adminSubAdmins = require('./adminSubAdmins');
const adminPermissions = require('./adminPermissions');
const adminSettings = require('./adminSettings');
const adminReassign = require('./adminReassign');
const { disableAdminModule } = require('../../middleware/moduleToggleMiddleware');

router.use('/auth', adminAuth);
router.use('/dashboard', adminDashboard);
router.use('/branches', adminBranches);
router.use('/managers', adminManagers);
router.use('/field-visitors', adminFieldVisitors);
router.use('/members', adminMembers);
router.use('/products', adminProducts);
router.use('/transactions', adminTransactions);
router.use('/wallets', adminWallets);
router.use('/company-transfers', adminCompanyTransfers);
router.use('/reports', adminReports);
router.use('/geo-tracking', disableAdminModule('geo-tracking'), adminGeoTracking);
router.use('/tasks', disableAdminModule('tasks'), adminTasks);
router.use('/attendance', disableAdminModule('attendance'), adminAttendance);
router.use('/notifications', adminNotifications);
router.use('/analytics', adminAnalytics);
router.use('/logs', disableAdminModule('logs'), adminLogs);
router.use('/fraud-alerts', adminFraudAlerts);
router.use('/sub-admins', adminSubAdmins);
router.use('/permissions', adminPermissions);
router.use('/settings', adminSettings);
router.use('/reassign', adminReassign);

module.exports = router;
